name: Rust Code Scan

on:
  push:
    branches:
      - main
    paths:
      - 'common/rust/evidence_api/src/**.rs'
      - 'common/rust/evidence_api/src/tdx/**.rs'
      - 'common/rust/evidence_api/src/tpm/**.rs'
      - '.github/workflows/pr-check-rust.yaml'
  pull_request:
    paths:
      - 'common/rust/evidence_api/src/**.rs'
      - 'common/rust/evidence_api/src/tdx/**.rs'
      - 'common/rust/evidence_api/src/tpm/**.rs'
      - '.github/workflows/pr-check-rust.yaml'
  workflow_dispatch:

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up Rust action
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0

      - name: Install dependencies
        run: |
          sudo apt update && yes | DEBIAN_FRONTEND=noninteractive sudo apt install -y libcryptsetup-dev clang protobuf-compiler protobuf-c-compiler libprotobuf-c-dev libprotobuf-c1 build-essential pkg-config libssl-dev

      - name: Run cargo check for evidence_api
        run: |
          cd common/rust/evidence_api/
          cargo check
          cargo fmt -- --check
          cargo clippy
          cargo install --locked cargo-deny
          cargo deny check
